### ISSUE TITLE
A single term is larger than the allowed chunk size.

### ISSUE THREAD

**Issue by alimirzaei** [jerryjliu/gpt_index#338]
I am getting this error but I can not understand which document has problem. How can I debug this issue?

**Comment by jerryjliu** [comment]
i'm sorry, this has popped up a bit. i'm still investigating why the code isn't handling this, but an explanation is that we split text into tokens via newlines or spaces, and we incrementally "build chunks" by adding tokens. Here it's saying that you have one "token" that's bigger than the text chunk size itself. You could try inserting a space every 1000 characters or so, maybe that would help

**Comment by jerryjliu** [comment]
@alimirzaei i've been trying to debug this issue, seems like a few people have raised this. what version are you on + could you send me some sample data to test this?

**Comment by jerryjliu** [comment]
Should be resolved with #361, try pip installing >=0.3.3

**Comment by xinmans** [comment]
i'am use llama-index==0.4.21, but still get this error

None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Token indices sequence length is longer than the specified maximum sequence length for this model (62216 > 1024). Running this sequence through the model will result in indexing errors
Traceback (most recent call last):
  File "a.py", line 6, in <module>
    index = GPTSimpleVectorIndex(documents)
  File "/home/xinmans/.local/lib/python3.8/site-packages/llama_index/indices/vector_store/vector_indices.py", line 83, in __init__
    super().__init__(
  File "/home/xinmans/.local/lib/python3.8/site-packages/llama_index/indices/vector_store/base.py", line 62, in __init__
    super().__init__(
  File "/home/xinmans/.local/lib/python3.8/site-packages/llama_index/indices/base.py", line 109, in __init__
    self._index_struct = self.build_index_from_documents(documents)
  File "/home/xinmans/.local/lib/python3.8/site-packages/llama_index/token_counter/token_counter.py", line 55, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
  File "/home/xinmans/.local/lib/python3.8/site-packages/llama_index/indices/base.py", line 278, in build_index_from_documents
    return self._build_index_from_documents(documents)
  File "/home/xinmans/.local/lib/python3.8/site-packages/llama_index/indices/vector_store/base.py", line 205, in _build_index_from_documents
    self._add_document_to_index(index_struct, d)
  File "/home/xinmans/.local/lib/python3.8/site-packages/llama_index/indices/vector_store/base.py", line 180, in _add_document_to_index
    nodes = self._get_nodes_from_document(document)
  File "/home/xinmans/.local/lib/python3.8/site-packages/llama_index/indices/base.py", line 260, in _get_nodes_from_document
    return get_nodes_from_document(
  File "/home/xinmans/.local/lib/python3.8/site-packages/llama_index/indices/node_utils.py", line 47, in get_nodes_from_document
    text_splits = get_text_splits_from_document(
  File "/home/xinmans/.local/lib/python3.8/site-packages/llama_index/indices/node_utils.py", line 27, in get_text_splits_from_document
    text_splits = text_splitter.split_text_with_overlaps(
  File "/home/xinmans/.local/lib/python3.8/site-packages/llama_index/langchain_helpers/text_splitter.py", line 147, in split_text_with_overlaps
    raise ValueError(
ValueError: A single term is larger than the allowed chunk size.
Term size: 3825
Chunk size: 3811Effective chunk size: 3811

**Comment by stevenylt** [comment]
I am getting this error as well with Chinese characters. I guess it might be space related because we don't use space in Chinese text.

**Comment by justinzyw** [comment]
Same problem here with Chinese characters. Hopefully this can be resolved in the code rather than adding spaces into the text every 100 chars.
